# Lecture 4 - (10/02/2026)

Today's Topics:

- Marks and Channels
- Temporal Data

## Marks and Channels

Altair recgonizes 4 different variable types:
- Nominal (Categorical)
- Quantative
- Ordinal
- Time-Based


Magnitude channels requires an ordered variable (Quantative/Ordinal)

Identity channels require a categorical attribute (Nominal)

![image](https://jenniewblog.wordpress.com/wp-content/uploads/2016/03/4.jpg?w=760)

In [ ]:
# if necessary
!pip install altair vega_datasets

In [71]:
import altair as alt
from vega_datasets import data
import pandas as pd
from altair import datum

[Vega Datasets](https://vega.github.io/vega-datasets/)

In [27]:
url = 'https://vega.github.io/vega-datasets/data/penguins.json'
data = pd.read_json(url)
data['index'] = data.index
data.head()

,Species,Island,Beak Length (mm),Beak Depth (mm),Flipper Length (mm),Body Mass (g),Sex,index
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,3
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,4

In [16]:
alt.Chart(data)

SchemaValidationError: '{'data': {'name': 'data-c46e1ab98ba3fb2ca8b5ae3c04ffafea'}}' is an invalid value.

'mark' is a required property

alt.Chart(...)

Notice how we cannot create a chart unless we specify the required mark

![image](../attachments/marks.png)

![image](../attachments/channels.png)

In [17]:
alt.Chart(data).mark_circle()

alt.Chart(...)

List of all marks in altair

[altair-viz.github.io/user_guide/marks.html](https://altair-viz.github.io/altair-viz-v4/user_guide/marks.html)


Notice how the marks in altair are the same ones used in vega

[https://vega.github.io/vega-lite/docs/mark.html](https://vega.github.io/vega-lite/docs/mark.html)


Often times you'll want to use vega-lite documentation since it's the underlying language for our visualizations

In [18]:
alt.Chart(data).mark_circle().encode(
    x='Beak Length (mm):Q'
)

alt.Chart(...)

or equivilantly

In [19]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q')
)

alt.Chart(...)

and if we want to change the zero

In [21]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False))
)

alt.Chart(...)

next we can split the data into multiple graphs by columns

#### Columns

In [ ]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    column='Species'  # notice how it automatically determines we're working with
)

alt.Chart(...)

#### Transformations

Let's try bar plotting the first 20 beak lengths

In [32]:
alt.Chart(data[:20]).mark_bar().encode(
    x='Beak Length (mm):Q',
    y='index:O'
)

alt.Chart(...)

Notice how we did this using pandas, but we can also do this using altair

In [ ]:
alt.Chart(data).mark_bar().encode(
    x='Beak Length (mm):Q',
    y='index:O'
).transform_filter(
    datum.index < 20
)

alt.Chart(...)

In [40]:
alt.Chart(data).mark_bar().encode(
    x='Beak Length (mm):Q',
    y='index:O'
).transform_filter(
    (datum.index  < 60) & (datum.Island == 'Biscoe')
)

alt.Chart(...)

First 60 values where their island was Biscoe

[Transform filter](https://altair-viz.github.io/altair-viz-v4/user_guide/transform/filter.html)

#### Properties

In [41]:
alt.Chart(data).mark_bar().encode(
    x='Beak Length (mm):Q',
    y='index:O'
).transform_filter(
    (datum.index  < 60) & (datum.Island == 'Biscoe')
).properties(height=200, width=700)

alt.Chart(...)

In [58]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    color='Species',
    size='Beak Length (mm):Q'
).properties(height=200, width=700)

alt.Chart(...)

#### Color Luminance

In [59]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    color=alt.Color('Beak Length (mm):Q', scale=alt.Scale(scheme='greys')),
    size='Beak Length (mm):Q'
).properties(height=200, width=700)

alt.Chart(...)

In [62]:
alt.Chart(data).mark_circle().encode(
    x=alt.X('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    color=alt.Color('Beak Length (mm):Q', scale=alt.Scale(scheme='purples')),
    size='Beak Length (mm):Q'
).properties(height=200, width=700)

alt.Chart(...)

In [64]:
alt.Chart(data).mark_circle().encode(
    y=alt.Y('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    color=alt.Color('Beak Length (mm):Q', scale=alt.Scale(scheme='purples')),
    size='Beak Length (mm):Q',
    x=alt.X('Species')
).properties(height=200, width=700)

alt.Chart(...)

In [66]:
alt.Chart(data).mark_circle().encode(
    y=alt.Y('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    color=alt.Color('Species:N', scale=alt.Scale(scheme='category10')),
    size='Beak Length (mm):Q',
    x=alt.X('Species')
).properties(height=200, width=700)

alt.Chart(...)

In [69]:
alt.Chart(data).mark_point().encode(
    y=alt.Y('Beak Length (mm):Q', scale=alt.Scale(zero=False)),
    shape='Species:N',
    color=alt.Color('Species:N', scale=alt.Scale(scheme='category10')),
    size='Beak Length (mm):Q',
    x=alt.X('Species:N')
).properties(height=200, width=700)

alt.Chart(...)

Expressiveness: 
- Visual encoding should express all of—and only—the information in the dataset.
- Ordered data should be shown in a way we perceive as ordered.
- Match channel and data characteristics.

Effectiveness:
- Encode most important attributes with highest-ranked channels

## Temporal Data

A temporal dataset is one where each attribute has a timestamp

- Sometimes is cyclic due to seasonality

Line chart / Dot plot:

Idea: One key, one value

- Data: Two quantitative attributes
- Mark: Points and Line connection marks between them
- Channels
  - Aligned lengths to express quant value
  - Seperated and ordered by key attribute into horizontal regions
- Task: Find trend
  - Connection marks emphasize ordering of items along key axis by explicitly showing relationship between one item and the next
- Scalability: hundreds of key levels, hundreds of value levels

### Bar vs Line

Depends on the key attribute:
- Bar charts if categorical
- Line charts if ordered

Do not use line charts for categorical key attributes!!!

- Violates expressiveness principle
- Implication of trend so strong that it overrides semantics!
  - ex: The more male a person is, the taller he/she is

![image](../attachments/bar_vs_line.png)

Note: Dual-Axis Line Charts
- Controversial
- Acceptable if commensurate
- Beware, very easy to mislead!

![image](../attachments/pitch.png)

Note: Indexed Line Charts

- Data: two quantitative attributes
  - One key and one value
- Derived data: new quantitative value attribute 
  - Index
  - Plot instead of original value
- Task: show change over time 
![image](../attachments/indexed_line.png)

In [72]:
df = px.data.stocks()
df.head()

         date      GOOG      AAPL      AMZN        FB      NFLX      MSFT
0  2018-01-01  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000
1  2018-01-08  1.018172  1.011943  1.061881  0.959968  1.053526  1.015988
2  2018-01-15  1.032008  1.019771  1.053240  0.970243  1.049860  1.020524
3  2018-01-22  1.066783  0.980057  1.140676  1.016858  1.307681  1.066561
4  2018-01-29  1.008773  0.917143  1.163374  1.018357  1.273537  1.040708

In [ ]:
alt.Chart(df).mark_bar().encode(
    x='date:T',
    y='MSFT:Q'
)

alt.Chart(...)

Good or Bad?

In [75]:
alt.Chart(df).mark_line().encode(
    x='date:T',
    y='MSFT:Q'
)

alt.Chart(...)

Good or Bad?

We can convert between [units of time](https://vega.github.io/vega-lite/docs/timeunit.html) using the built in functions

In [83]:
alt.Chart(df).mark_line().encode(
    x='yearmonth(date):T',
    y='MSFT:Q'
)

alt.Chart(...)

In [85]:
alt.Chart(df).mark_bar().encode(
    x='yearmonth(date):T',
    y='MSFT:Q'
)

alt.Chart(...)

These functions are called aggregation functions because they take a series of values and **bin** them together into one value

In [ ]:
alt.Chart(df).mark_rect().encode(
    x='year(date):T',
    y='month(date):T',
    color='MSFT'
)

alt.Chart(...)

But what if we want to plot multiple lines?

In [108]:
alt.Chart(df).transform_fold(
    ['GOOG', 'AAPL', 'AMZN', 'MSFT', 'FB'],
    as_=['stock', 'price']
).mark_line().encode(
    x='date:T',
    y='price:Q',
    color='stock:N'
)

alt.Chart(...)

The fold transform is, in short, a way to convert wide-form data to long-form data directly without any preprocessing. Fold transforms are the opposite of the Pivot.

See [wide form vs long form](https://altair-viz.github.io/user_guide/data.html#data-long-vs-wide)